extra_docs/examples/javascript/browser/browser-example.html
package.json
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts

```
[x] Bugfix
[ ] Feature
[x] Build related changes
```
Refresh token timer is reset with no information of how much time it lefts, and the current token can be invalid from the beginning or become invalid before the next refresh.
Always refresh the token when start the SDK.
```
[ ] Yes
[x] No
```

Fix refresh token time inconsistency when initializing

---

src/api/dataops/dataset.ts
src/api/dataops/deleteQuery.ts
src/api/dataops/filteringApi.spec.ts
src/api/dataops/filteringApi.ts
src/api/dataops/filteringCondition.spec.ts
src/api/dataops/filteringCondition.ts
src/api/dataops/query.interfaces.ts
src/api/dataops/selectQuery.ts
src/api/dataops/updateQuery.ts
src/index.ts
src/internal/query.ts

```
[ ] Bugfix
[x] Feature
```
Methods like `isEqualTo()` and others are able to handle only `string` type arguments 
Issue https://github.com/jexia/jexia-sdk-js/issues/22
Next methods accept any type of arguments:
* isGreaterThan
* isLessThan
* isEqualTo
* isDifferentFrom
* isEqualOrGreaterThan
* isEqualOrLessThan
* isNull
* isNotNull
* isInArray
* isNotInArray
* isBetween
These ones accept only string:
* isLike
* satisfiesRegexp
In case customer provides dataset interface, typescript will give a hint which type of argument …

Allow using any types for conditional methods

---

extra_docs/quickstart.md
spec/testUtils.ts
src/api/dataops/queries/baseQuery.spec.ts
src/api/dataops/queries/baseQuery.ts
src/api/dataops/queries/filterableQuery.spec.ts
src/internal/query.spec.ts
src/internal/query.ts

close #28
```
[ ] Bugfix
[x] Feature
```
Aggregation functions are not supported
Issue Number: #28 
Support functions `SUM`, `AVG`, `MIN`, `MAX`, `EVERY` and `COUNT`
```
[ ] Yes
[x] No
```

feat(query): aggregation functions support

---

src/api/core/client.ts
src/api/logger/logger.spec.ts
src/api/logger/logger.ts
src/api/logger/loggerModule.spec.ts
src/api/logger/loggerModule.ts
src/api/logger/public-api.ts
src/browser.ts
src/internal/requestAdapter.ts
src/node.ts

LoggerModule can be added to Jexia client init function and any module can use it to print different level messages.
Logger can be configured to print messages only with specific level and/or from a specific module.
This PR does not include logger usage, except one example in src/internal/requestAdapter.ts:61

feat(logger): create logger module

---

extra_docs/quickstart.md
src/api/dataops/dataset.spec.ts
src/api/dataops/dataset.ts

First part for updating to the current dataset contracts, allowing user to insert records passing an array or an object.

Allow single record object notation for inserting records

---

src/api/core/queries/filterableQuery.spec.ts
src/api/core/queries/filterableQuery.ts
src/api/core/queries/relatedQuery.ts
src/api/core/queries/selectQuery.spec.ts
src/api/core/queries/selectQuery.ts
src/api/core/resource.ts
src/api/dataops/dataset.ts
src/api/dataops/filteringApi.ts
src/internal/query.spec.ts
src/internal/query.ts

```
[ ] Bugfix
[x] Feature
```
Select query supports `related()` method which is able to populate nested fields (any level of nesting)
```
[x] Yes
[ ] No
```
`relation()` method is not supported anymore

feat(relation): populate nested resources

---

e2e/config.ts
e2e/management.ts
e2e/stories/relations/related.e2e.ts
e2e/teardowns.ts

Basic e2e tests for the related() method:
```
PASS  e2e/stories/relations/related.e2e.ts (24.502s)
Populate related fields
√ should select all nested fields by default (951ms)
√ should select only provided fields and id (569ms)
√ should populate all fields from 2-nd level relation (593ms)
√ should select only provided fields and id from the 2-nd level relation (500ms)
√ should select only provided fields and id from both nested relations (1016ms)
```

test(related): e2e tests for the related() method

---

spec/queryAction.ts
spec/requestMethod.ts
spec/testUtils.ts
src/api/core/queries/actionQuery.ts
src/api/core/queries/baseQuery.spec.ts
src/api/core/queries/baseQuery.ts
src/api/core/queries/deleteQuery.spec.ts
src/api/core/queries/deleteQuery.ts
src/api/core/queries/filterableQuery.spec.ts
src/api/core/queries/insertQuery.spec.ts
src/api/core/queries/insertQuery.ts
src/api/core/queries/selectQuery.ts
src/api/core/queries/updateQuery.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/dataops/dataset.spec.ts
src/api/dataops/dataset.ts
src/api/fileops/fileset.spec.ts
src/api/fileops/fileset.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/internal/executer.interfaces.ts
src/internal/executer.spec.ts
src/internal/executer.ts
src/internal/requestAdapter.interfaces.ts
src/internal/requestAdapter.spec.ts
src/internal/requestAdapter.ts

```
[x] Bugfix
[ ] Feature
```
Attach/detach filter param is optional in sdk, but required in the API. The request verb accepted is `PUT` while sdk is sending `PATCH`
Make param required and change method to `PUT`
```
[ ] Yes
[x] No
```

Fix attach/detach make filter required and change method to PUT 

---

spec/resource.ts
spec/testUtils.ts
src/api/core/queries/actionQuery.spec.ts
src/api/core/queries/baseQuery.spec.ts
src/api/core/queries/deleteQuery.spec.ts
src/api/core/queries/filterableQuery.spec.ts
src/api/core/queries/insertQuery.spec.ts
src/api/core/queries/selectQuery.spec.ts
src/api/core/queries/updateQuery.spec.ts
src/internal/executer.spec.ts
src/internal/requestAdapter.interfaces.ts
src/internal/requestAdapter.spec.ts
src/internal/requestAdapter.ts

This PR is dependant on https://github.com/jexia/jexia-sdk-js/pull/101
```
[x] Bugfix
[ ] Feature
```
Attach/detach request is calling `response.json()` but the response is empty (so, not a valid json) so an error is thrown
Introduced a new parameter for `RequestAdatpter:execute()` to ignore the response and return an empty object instead.
```
[ ] Yes
[x] No
```

Fix attach/detach parsing empty response

---

extra_docs/relations/README.md
src/api/core/queries/actionQuery.spec.ts
src/api/core/queries/actionQuery.ts
src/api/core/resource.ts
src/api/dataops/dataset.ts
src/api/fileops/fileset.ts
src/internal/query.spec.ts
src/internal/query.ts

```
[ ] Bugfix
[X] Feature
```
`attach()` and `detach()` methods can only be filtered by passing filter criterion.
You can pass an array either of ids, or objects with ids.
```
[ ] Yes
[X] No
```

Allow attach/detach to receive array of objects/ids as filter

---

src/api/realtime/channel.ts
src/api/realtime/realTime.interfaces.ts

When a customer publishes two identical messages to the channel, SDK can mess up the responses. Adding `correlation_id` solves this problem (this could happen only for the messages in a row, so `Math.random()` is good enough).

add correlation id

---

e2e/stories/ums/ums.e2e.ts
src/api/core/componentStorage.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/ums/umsModule.ts

```
[x] Bugfix
[ ] Feature
```
User Management Service module `getUser()` method does not allow to fetch a user by email.
Token Manager is able to keep several aliases for each token pair so that a user can be fetched by their email.
```
[ ] Yes
[x] No
```

fix(ums): allow fetching user by email

---

extra_docs/dataset/README.md
extra_docs/jfs/README.md
src/api/core/queries/actionQuery.spec.ts
src/api/core/queries/baseQuery.spec.ts
src/api/core/queries/baseQuery.ts
src/api/core/queries/insertQuery.spec.ts
src/api/core/queries/insertQuery.ts
src/api/core/queries/selectQuery.spec.ts
src/api/core/queries/updateQuery.spec.ts

Old data request syntax:
```javascript
dataet.select()
.execute()
.then(result => {
// enjoy your result
})
.catch(error => // do something with error)
```
new syntax:
```javascript
dataset.select()
.subscribe(result => {
// enjoy your result
}, error => // do something with error);
```

feat(queries): migrate data queries to the observables

---

extra_docs/dataset/README.md
src/api/dataops/dataOperationsModule.spec.ts
src/api/dataops/dataOperationsModule.ts
src/api/fileops/fileOperationsModule.spec.ts
src/api/fileops/fileOperationsModule.ts

Currently, it is only possible to get one resource (either dataset or fileset at a time):
```typescript
const posts = dataOperation.dataset("posts");
const authors = dataOperation.dataset("authors");
```
This PR adds `datasets()` and `filesets()` methods which allow getting a list of resources:
```typescript
const [posts, authors] = dataOperation.datasets(["posts", "authors"]);
```
Setting a type of each resource is also supported:
```typescript
const [posts, authors] = dataOperation.datasets<Post, Author>(["posts", "authors"]);
```

feat(sets): allow to initiate a list of resources at a time

---

src/config/index.ts

```
[X] Bugfix
[ ] Feature
```
While loading sdk in browser, a `ReferenceError` is thrown because it cannot find `process` variable (see screenshot)
Check whether `window` object is defined, so we know whether we're in a browser.
```
[ ] Yes
[X] No
```

fix(browser): when calling global "process" an error is being thrown

---

e2e/config.ts
e2e/management.ts
e2e/stories/dataset/aggregations.e2e.ts
extra_docs/dataset/README.md
src/internal/query.ts

Add an alias to aggregation functions:
before:
```
posts.select()
.fields("author", { fn: "max", field: "likes" })
.subscribe(result => {
/* the result is:
[
{ author: "Tom", "max": 10 },
{ author: "Harry", "max": 24 },
]
*/
});
```
after:
```
posts.select()
.fields("author", { fn: "max", field: "likes": alias: "max likes" })
.subscribe(result => {
/* the result is:
[
{ author: "Tom", "max likes": 10 },
{ author: "Harry", "max likes": 24 },
]
*/
});
```

feat(query): add alias support to query aggregation functions

---

e2e/lib/ums.ts
e2e/stories/ums/ums.e2e.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/internal/query.ts
tsconfig.json

BREAKING CHANGE (UMS)
All extra fields for the user signup are provided as an extra option:
```javascript
ums.signup(user, { age: 33, city: "Arnhem" });
```
Extra fields are merged with credentials:
```javascript
ums.signup({ ...user, age: 33, city: "Arnhem" });
```
```
[x] Yes
[ ] No
```

fix(ums): merge user credentials and extra fields for signup

---

e2e/stories/dataset/output-record.e2e.ts
src/api/core/queries/baseQuery.ts
src/api/core/queries/selectQuery.spec.ts
src/api/dataops/dataset.spec.ts
src/api/dataops/dataset.ts

```
[ ] Bugfix
[x] Feature
```
`dataset.select()` method does not have arguments, in order to select certain fields `fields()` method should be called.
Fields can be provided as an argument to `dataset.select()` function:
```
dataset.select("user", "comments").subescribe();
```
this code is equal to the following:
```
dataset.select().fields("user", "comments").subescribe();
```
Both approaches can be used simultaneously.
```
[ ] Yes
[x] No
``` …

feat(select-query): add fields as a select query argument

---

README.md
e2e/README.md
e2e/browser/index.html
e2e/teardowns.ts
spec/testUtils.ts
src/api/core/tokenManager.ts
src/internal/executer.spec.ts
src/internal/executer.ts

```
[ ] Bugfix
[X] Feature
```
Currently projects API URLs are hosted under `<project-id>.app.jexia.com`
Projects are now hosted under `<project-zone>.<project-id>.app.jexia.com`, so zone config parameter is required. The current projects will keep working without changes for a while.
```
[ ] Yes
[X] No
```

feat: add project zone config to client initialization

---

e2e/teardowns.ts
src/api/realtime/realTimeModule.spec.ts
src/api/realtime/realTimeModule.ts
src/config/config.spec.ts
src/config/config.ts

```
[X] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
Currently when user pass `projectURL` only, RTC url is wrongly formatted.
WS url follows the same rules and of api urls.
```
[ ] Yes
[X] No
```

fix(rtc): wrong url when using projectURL config param

---

src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/config/config.spec.ts
src/config/config.ts

```
[X] Bugfix
[ ] Feature
```
Currently when some authentication error is thrown, there is no http status code for the user, just a plain message.
Issue Number: #180 
`httpStatus` object is included in the error, with `code` and `statusText` available.
```
[ ] Yes
[X] No
```

fix(token-manager): throw http status when it occurs

---

src/internal/executer.spec.ts
src/internal/executer.ts
src/internal/utils/queryParam.spec.ts
src/internal/utils/queryParam.ts

```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
Current method that parses query params object it's inside `RequestExecuter` class.
function was extracted and can be imported anywhere
```
[ ] Yes
[X] No
```

refactor(request-executer): extract method that parses query params

---

package-lock.json
package.json
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/config/config.ts
src/internal/utils/index.ts
src/internal/utils/token.spec.ts
src/internal/utils/token.ts

```
[x] Bugfix
[ ] Feature
```
Refreshing a token was based on a fixed amount of `ms` and it was set to interval. This brings a couple odd situations.
1. When a token expired and got refreshed 3 times, it also set 3 intervals. What result in 9 refreshes in the end.
2. When you visit the page after a period of time (before the expiration). The delay never hits the expiration.
The tokenmanager set the new delay based on the `exp` of the token. Also it …

fix(token): timeout for refreshing token based on expiration

---

src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts

```
[x] Bugfix
[ ] Feature
```
The `timeout` was not set again after the previous one ends.
A new timeout is set when the previous has been ended.
```
[ ] Yes
[x] No
```

fix(token): restart timeout after digest ends

---

package-lock.json
package.json
spec/testUtils.ts
spec/token.ts
src/api/core/componentStorage.spec.ts
src/api/core/componentStorage.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/config/config.ts
src/internal/utils/token.spec.ts
src/internal/utils/token.ts

```
[ ] Bugfix
[x] Feature
```
Currently we have a digest in place (`setTimeout`) that will execute when the token expired to fetch a new one.
To be **100%** sure that we have a valid token, we do a simple check before a request is made. If the token got expired, fetch a new token just before the actual request can be made and use that one instead.
```
[ ] Yes
[x] No
```

feat(token): refresh token before a request made if digest fails

---

src/api/core/componentStorage.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/config/message.ts

```
[ ] Bugfix
[x] Feature
```
Currently, `ums.getUser()` cannot be fallback on the alias that has been set as the DEFAULT.
For `ums.getUser()` you can now omit the `alias` param so it can fallback on the alias that set as DEFAULT.
```
[ ] Yes
[x] No
```

feat(ums): getUser can fallback on the default alias if set

---

src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts

```
[ ] Bugfix
[x] Feature
```
Currently there is no way to get the current user that is logged.
This PR introduce 
- a new api method to get the current logged-in user via `ums.isLoggedIn([alias: optional]).subscribe()`
- changed the `ums.signIn()` to return the current user that has been logged in, instead of the token. Tokens are no concern of the user as it will handle all by the SDK.
```
[x] Yes
[ ] No
```
The `ums.signIn()` method will not …

feat(ums): introduce currentUser

---

src/api/core/filteringApi.spec.ts
src/api/core/filteringApi.ts

```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
The docs talk about `satisfiesRegex` but in the code it is `satisfiesRegexp`
We unify it to just `satisfiesRegex`
```
[x] Yes
[ ] No
```
Instead of using `satisfiesRegexp` you should use `satisfiesRegex`
```
.where(field => field("title").satisfiesRegex('a-z0-9'))
```

refactor(filter): rename satisfiesRegexp to satisfiesRegex

---

src/api/core/client.ts
src/api/core/dispatcher.spec.ts
src/api/core/dispatcher.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/realtime/realTimeModule.spec.ts
src/api/realtime/realTimeModule.ts
src/api/realtime/websocket.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/config/message.ts
src/internal/utils/token.spec.ts

```
[x] Bugfix
[x] Feature
```
The RTC will throw an error when using the UMS.
RTC will listen to system events and act on that instead of open the connection directly.
- So when a user is logged in, it will open or set a new token for the current connection.
- When you switch a user it will set the token for that user to the current connection.
- It will close the connection when a user is logging out.
- it will set the new token after a token …

fix(rtc): when using the ums

---

src/api/realtime/realTimeModule.spec.ts
src/api/realtime/realTimeModule.ts

```
[x] Bugfix
[ ] Feature
```
`ums.signOut()` should close the connection only instead terminate the whole RTC.
Just close the RTC connection
```
[ ] Yes
[x] No
```

fix: close RTC connection only on ums.signOut

---

src/api/core/client.spec.ts
src/api/core/client.ts
src/api/core/dispatcher.spec.ts
src/api/core/dispatcher.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/realtime/realTimeModule.spec.ts
src/api/realtime/realTimeModule.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/internal/utils/index.ts

```
[ ] Bugfix
[x] Feature
```
There is no way to subscribe to events that are fired in the SDK.
We exposed a `.on()` method on the client to subscribe on SDK events.
```
[ ] Yes
[x] No
```

feat(dispatcher): expose .on method to the client

---

src/api/realtime/realTimeModule.spec.ts
src/api/realtime/realTimeModule.ts
src/api/realtime/websocket.ts

```
[x] Bugfix
[ ] Feature
```
Currently the RTC wont send any new messages after a user is login - logout - login again. 
It will handle open - close - open connections better.
```
[ ] Yes
[x] No
```

fix(rtc): open-close-open will fail to send new messages
