package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```

Update semantic release tools and add changelog

---

CONTRIBUTING.md
README.md
extra_docs/summary.json
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

docs(links): fix broken links on api docs generation

---

extra_docs/quickstart.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
fix #3

docs(quickstart): fix example code  error

---

package-lock.json
package.json
spec/clientTest.ts
src/api/auth/BaseAuth.ts
src/api/auth/apiKeyAuth.ts
src/api/auth/index.ts
src/api/auth/userCredentialsAuth.ts
src/api/core/client.ts
src/api/core/componentStorage.ts
src/api/core/module.ts
src/api/core/resource.ts
src/api/core/tokenManager.ts
src/api/dataops/dataOperationsModule.ts
src/api/dataops/dataRequest.ts
src/api/dataops/dataset.ts
src/api/dataops/deleteQuery.ts
src/api/dataops/filteringApi.ts
src/api/dataops/filteringCondition.ts
src/api/dataops/injectionTokens.ts
src/api/dataops/insertQuery.ts
src/api/dataops/queryInterfaces.ts
src/api/dataops/selectQuery.ts
src/api/dataops/updateQuery.ts
src/api/realtime/rtcModule.ts
src/index.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Increasing public API doc coverage

---

src/api/dataops/filteringCondition.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Test
```
```
[ ] Yes
[x] No
```

test(filtering-condition): increasing test coverage

---

src/api/dataops/deleteQuery.spec.ts
src/api/dataops/deleteQuery.ts
src/api/dataops/query.interfaces.ts
src/api/dataops/selectQuery.spec.ts
src/api/dataops/selectQuery.ts
src/api/dataops/updateQuery.spec.ts
src/api/dataops/updateQuery.ts

```
[ ] Bugfix
[x] Feature
```
Methods that receive field names just accept a sequence of strings for each argument.
Issue Number: #8
Methods that receive field names now accept an array of strings at the first argument.
```
[ ] Yes
[x] No
```

feat(array-fields): overloads all methods that receive field names to accept array

---

extra_docs/typescript.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(links): fix typescript guide links

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```

ci(semantic-version): updating tooling

---

extra_docs/realtime.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(real-time): add real-time module documentation

---

package-lock.json
package.json
src/api/dataops/deleteQuery.ts
src/api/dataops/filteringApi.ts
src/api/dataops/selectQuery.ts
src/api/dataops/updateQuery.ts
src/internal/query.ts

```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```
Typescript version 2.9 introduced a breaking change - `keyof T` can be not only `string` but also `number` or `symbol`:
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-29
This PR adds `Extract<keyof T, string>` restriction to avoid TS errors.

build(typecript): upgrade Typescript to the version 2.9.2

---

.gitignore
src/api/auth/BaseAuth.ts
src/api/auth/apiKeyAuth.spec.ts
src/api/auth/apiKeyAuth.ts
src/api/auth/userCredentialsAuth.spec.ts
src/config/config.ts

Changing AUTH API endpoints following new AppEngine management API

feat(auth): change Auth API endpoints

---

src/api/dataops/queries/baseQuery.spec.ts
src/api/dataops/queries/baseQuery.ts
src/api/dataops/queries/deleteQuery.spec.ts
src/api/dataops/queries/insertQuery.spec.ts
src/api/dataops/queries/insertQuery.ts
src/api/dataops/queries/selectQuery.spec.ts
src/api/dataops/queries/updateQuery.spec.ts
src/config/config.ts
src/internal/executer.spec.ts
src/internal/executer.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(query): remove record api

---

e2e/lib/ums.ts
e2e/stories/ums.e2e.ts
e2e/teardowns.ts
package.json
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/config/config.ts
src/internal/requestAdapter.ts

+ sign up a new user
+ e2e tests

Authenticate user

---

e2e/stories/ums.e2e.ts
extra_docs/ums/ums_draft.md
src/api/core/tokenManager.ts
src/api/dataops/dataOperationsModule.ts
src/internal/executer.ts

task: [https://jexia.myjetbrains.com/youtrack/issue/JEXIA-1470](url)

feat(ums): specify user to the dataset request

---

e2e/README.md
e2e/browser/index.html
spec/testUtils.ts
src/api/fileops/fileOperationsModule.spec.ts
src/api/fileops/fileUploader.ts

- add fileOperationsModule tests
- add upload file browser example
- fix run e2e tests readme

task(fileset): append data field

---

package.json
spec/queryAction.ts
spec/testUtils.ts
src/api/dataops/queries/baseQuery.spec.ts
src/api/dataops/queries/baseQuery.ts
src/api/dataops/queries/deleteQuery.spec.ts
src/api/dataops/queries/insertQuery.spec.ts
src/api/dataops/queries/insertQuery.ts
src/api/dataops/queries/updateQuery.ts
src/internal/executer.interfaces.ts
src/internal/executer.spec.ts
src/internal/executer.ts
src/internal/query.spec.ts
src/internal/query.ts

Refactor BaseQuery and RequestExecutor

---

src/api/dataops/queries/baseQuery.spec.ts
src/api/dataops/queries/baseQuery.ts
src/internal/executer.interfaces.ts
src/internal/executer.spec.ts
src/internal/executer.ts
src/internal/query.spec.ts
src/internal/query.ts

Merged: ~~depends on https://github.com/jexia/jexia-sdk-js/pull/62~~

Update dataset API to use query params

---

e2e/management.ts
e2e/stories/create-record.e2e.ts
e2e/stories/update-record.e2e.ts
e2e/teardowns.ts

- Fix creating required fields
- Add test case for CREATE
- Add test cases for UPDATE

Update e2e tests for Create/Retrieve/Update datasets

---

e2e/lib/fileset.ts
e2e/management.ts
e2e/stories/jfs.e2e.ts
e2e/stories/rtc.e2e.ts
e2e/stories/ums.e2e.ts
e2e/teardowns.ts
package.json
spec/testUtils.ts
src/api/core/client.spec.ts
src/api/core/componentStorage.spec.ts
src/api/core/componentStorage.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/fileops/fileOperationsModule.spec.ts
src/api/fileops/fileOperationsModule.ts
src/api/fileops/fileUploader.spec.ts
src/api/fileops/fileUploader.ts
src/api/fileops/fileops.interfaces.ts
src/api/fileops/fileset.spec.ts
src/api/fileops/fileset.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/node.ts
tslint.json

- formData reusable fix
- file uploader unit tests

file uploader tests

---

e2e/management.ts
e2e/stories/create-record.e2e.ts
e2e/stories/delete-record.e2e.ts
e2e/stories/select-record.e2e.ts
e2e/stories/update-record.e2e.ts
e2e/teardowns.ts
extra_docs/quickstart.md
package.json
spec/queryAction.ts
spec/testUtils.ts
src/api/dataops/dataset.spec.ts
src/api/dataops/dataset.ts
src/api/dataops/filteringApi.spec.ts
src/api/dataops/filteringApi.ts
src/api/dataops/filteringCondition.spec.ts
src/api/dataops/filteringCondition.ts
src/api/dataops/queries/baseQuery.spec.ts
src/api/dataops/queries/baseQuery.ts
src/api/dataops/queries/deleteQuery.spec.ts
src/api/dataops/queries/filterableQuery.ts
src/api/dataops/queries/insertQuery.spec.ts
src/api/dataops/queries/insertQuery.ts
src/api/dataops/queries/updateQuery.spec.ts
src/api/dataops/queries/updateQuery.ts
src/internal/executer.interfaces.ts
src/internal/executer.spec.ts
src/internal/executer.ts
src/internal/query.spec.ts
src/internal/query.ts
src/internal/utils.ts

```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[X] No
```

refactor(dataset): Update dataset to the contracts

---

e2e/stories/select-record.e2e.ts

```
[ ] Bugfix
[ ] Feature
[X] Tests updates
```
```
[ ] Yes
[X] No
```

test(e2e): update filtering test cases

---

README.md
extra_docs/examples/javascript/browser/browser-example.html
extra_docs/examples/javascript/node/node-example.js
extra_docs/examples/javascript/node/realTimeExample.js
extra_docs/examples/javascript/node/realTimeExample.ts
extra_docs/examples/javascript/node/rest_get_all_records.ts
extra_docs/examples/javascript/node/testFeatures.js
extra_docs/examples/javascript/node/tsnode-example.ts
extra_docs/quickstart.md
extra_docs/realtime.md
extra_docs/typescript.md
package.json
src/api/core/client.ts
src/api/dataops/dataOperationsModule.ts
src/api/dataops/dataset.ts
src/api/dataops/queries/deleteQuery.ts
src/api/dataops/queries/filterableQuery.ts
src/api/dataops/queries/insertQuery.ts
src/api/dataops/queries/selectQuery.ts
src/api/dataops/queries/updateQuery.ts
src/api/realtime/realTimeModule.ts
tslint.json

- Updates outdated documentation
- Updates syntax of the examples to follow our conventions
- Change doc theme to material (see https://compodoc.app/guides/themes.html)
```
```
```
[ ] Yes
[X] No
```

Update overall documentation

---

e2e/stories/delete-record.e2e.ts
e2e/stories/output-record.e2e.ts
e2e/stories/select-record.e2e.ts

```
[ ] Bugfix
[ ] Feature
[X] E2E Tests
```
```
[ ] Yes
[X] No
```

Update e2e tests

---

e2e/README.md
package.json
scripts/env-check.js

```
[ ] Bugfix
[ ] Feature
[X] CI related changes
```
```
[ ] Yes
[X] No
```

Validate e2e test env variables and update docs

---

extra_docs/jfs/README.md
src/api/fileops/fileset.spec.ts
src/api/fileops/fileset.ts

- add fileset CRUD unit tests
- update documentation

Add fileset unit tests

---

e2e/stories/select-record.e2e.ts

```
[ ] Bugfix
[ ] Feature
[X] E2E Tests
```
```
[ ] Yes
[X] No
```

Add date/datetime dataset e2e test cases

---

extra_docs/dataset/README.md
extra_docs/quickstart.md
extra_docs/summary.json
src/api/dataops/filteringApi.ts

```
[ ] Bugfix
[ ] Feature
```

Enhance datasets documentation

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```

build(npm): include node-fetch and ws dependencies

---

src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts

```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
[x] Other... Please describe: Improve test coverage
```
```
[ ] Yes
[x] No
```

refactor(tokenmanager): refactor tokenManager and improve test coverage

---

src/api/core/queries/actionQuery.ts
src/api/dataops/dataset.spec.ts
src/api/dataops/dataset.ts
src/api/fileops/fileset.spec.ts
src/api/fileops/fileset.ts
src/internal/utils/queryActionType.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

Add detach operation to datasets and filesets

---

.circleci/config.yml

```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```

ci(opencollective): disable opencollective on circleci

---

e2e/lib/utils.ts
e2e/stories/dataset/delete-record.e2e.ts
e2e/stories/dataset/select-record.e2e.ts
e2e/stories/dataset/update-record.e2e.ts
e2e/stories/jfs/jfs-delete.e2e.ts
e2e/stories/jfs/jfs-select.e2e.ts
e2e/stories/jfs/jfs-update.e2e.ts
e2e/stories/relations/attach-detach.e2e.ts

```
[ ] Bugfix
[ ] Feature
[x] E2E Tests
```
```
[ ] Yes
[x] No
```

E2E tests for attach/detach

---

package.json

```
[ ] Bugfix
[ ] Feature
```
Having a npm script to serve docs locally so it helps updating documentation. 
```
[ ] Yes
[ ] No
```

build: add script to serve/watch docs

---

extra_docs/relations/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

Documentation for attach/detach

---

src/api/realtime/realTimeModule.ts

docs(rtm): suppress docs generation for the declared interfaces

---

extra_docs/jfs/README.md

- [x ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
```
[ ] Yes
[ x] No
```

Fix for broken link to docs

---

build/webpack.config.js
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
`uglifyjs-webpack-plugin` is deprecated and contains some vulnerable packages.
The package was replaced by [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin)
```
[ ] Yes
[x] No
```

build: replace deprecated uglifyjs with terser weback plugin

---

e2e/config.ts
e2e/management.ts
e2e/stories/ums/ums-crud.e2e.ts
e2e/stories/ums/ums.e2e.ts
e2e/teardowns.ts
extra_docs/ums/README.md
package-lock.json
package.json
src/api/core/queries/filterableQuery.ts
src/api/core/queries/insertQuery.spec.ts
src/api/core/queries/insertQuery.ts
src/api/core/queries/updateQuery.ts
src/api/core/resource.ts
src/api/dataops/dataset.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/internal/executer.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

UMS CRUD operations (except INSERT)

---

e2e/stories/ums/ums.e2e.ts

```
[ ] Bugfix
[ ] Feature
[X] Remove test deprecations
```
```
[ ] Yes
[X] No
```

test(ums): remove e2e deprecations

---

e2e/config.ts
e2e/management.ts
e2e/stories/ums/ums.e2e.ts
extra_docs/ums/README.md
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/config/config.ts

```
[ ] Bugfix
[X] Feature
```
In order to change an user's password, the user should know the current one. 
Now it's possible to reset an user's password with two steps, first request the reset, then with token change to a new password.
```
[ ] Yes
[X] No
```

feat(ums): reset user's password

---

package-lock.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

build: upgrade vulnerable packages

---

e2e/stories/dataset/select-record.e2e.ts
e2e/teardowns.ts
src/api/core/resource.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/fileops/fileUploader.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/config/config.spec.ts
src/config/config.ts
src/config/index.ts
src/internal/executer.spec.ts
src/internal/executer.ts

```
[X] Bugfix
[ ] Feature
```
Modules like UMS, token manager and file uploads through filesets are still using the legacy URL without the project zone.
All modules will get the base url through a common function.
```
[ ] Yes
[X] No
```

fix(project-url): enforce use of the new url throughout the modules

---

README.md
package-lock.json
package.json

```
[X] Bugfix
[ ] Feature
```
Issue Number: #169
```
[ ] Yes
[X] No
```

fix(node-ws): warnings on versions of node higher than 10 

---

package-lock.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

fix(npm): audit vulnerable packages

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```

build: upgrade vulnerable deps

---

src/api/core/queries/filterableQuery.spec.ts
src/api/core/queries/updateQuery.spec.ts
src/api/dataops/dataOperationsModule.spec.ts

```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```

style(tests): change suite titles

---

e2e/stories/ums/ums-crud.e2e.ts
e2e/stories/ums/ums.e2e.ts
src/api/ums/ums.types.ts
src/api/ums/umsModule.ts

```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
UMS Types and Interfaces are in the module file
Moving it to a new file, that's the first step for the next changes (Social authentication in UMS)
```
[ ] Yes
[X] No
```

refactor(ums-module): extract types to separate file

---

src/api/ums/ums.functions.spec.ts
src/api/ums/ums.functions.ts
src/api/ums/ums.types.spec.ts
src/api/ums/ums.types.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/config/config.ts

```
[ ] Bugfix
[X] Feature
```
Currently UMS users can only log in through regular credentials (email/password)
UMS users have now option to login through OAuth.
```
[ ] Yes
[X] No
```
This PR depends on #177 and #178 , after these are merged this branch needs to be rebased to remove duplicate commits

feat(ums): add oauth support

---

README.md

```
[ ] Bugfix
[ ] Feature
```
There is no yarn command for installing
Add yarn command to the docs
```
[ ] Yes
[x] No
```

docs: add yarn install command

---

src/config/config.ts

```
[x] Bugfix
[ ] Feature
```
The token `refresh` is calling a wrong url.
A valid URL is given.
```
[ ] Yes
[x] No
```

fix: refresh url to be valid

---

src/api/core/componentStorage.spec.ts
src/api/core/componentStorage.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts
src/config/config.ts

```
[ ] Bugfix
[x] Feature
```
There is no `sign-out` function to remove the keys for an user.
A new function has been introduced `ums.signOut('john@doe.com')` to remove all tokens that belongs to the user and set, if needed, a new default tokens.
```
[ ] Yes
[x] No
```

feat(ums): introduce sign-out

---

e2e/stories/dataset/select-record.e2e.ts
e2e/stories/init/init.e2e.ts
e2e/stories/ums/ums.e2e.ts
e2e/teardowns.ts
spec/testUtils.ts
spec/token.ts
src/api/core/client.ts
src/api/core/componentStorage.ts
src/api/core/tokenManager.spec.ts
src/api/core/tokenManager.ts
src/api/dataops/dataOperationsModule.ts
src/api/fileops/fileUploader.ts
src/api/ums/ums.functions.spec.ts
src/internal/executer.spec.ts
src/internal/utils/token.spec.ts
src/internal/utils/token.ts
tslint.json

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
There is was no check on the semicolon at all.
Adding a new rule for the semicolon.
```
[ ] Yes
[x] No
```

chore: add semicolon rule

---

src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts

```
[ ] Bugfix
[x] Feature
```
There is no way to check if a user is logged in.
Adding a way to check if a user is logged in.
```
[ ] Yes
[x] No
```

feat(ums): introduce isLoggedIn method

---

src/api/ums/umsModule.spec.ts
src/api/ums/umsModule.ts

```
[ ] Bugfix
[x] Feature
[x] Refactoring (no functional changes, no api changes)
```
Not really new, but this PR will add a new `switchUser` method to switch between logged in users. The old `setDefault` will be deprecated with this change and be removed in the future.
We add some extra checks on the alias and the token.
```
[x] Yes
[ ] No
```
Th `setDefault` method will be deprecated with this change and be removed in the future.

feat(ums): introduce switch user

---

src/api/realtime/realTimeModule.spec.ts
src/api/realtime/realTimeModule.ts

```
[x] Bugfix
[ ] Feature
```
Currently there is no way to connect the RTC with the current, in localstorage, available tokens.
The RTC will auto connect when it detect any available token(s). 
```
[ ] Yes
[x] No
```

fix(rtc): auto connect when there are tokens available
